[package]
name = "client"
version = "0.1.0"
authors = ["Adam R Bell <a_0x07@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "~1.5"
